# Generated by Django 5.0.6 on 2025-06-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='IPO',
            fields=[
                ('ipo_id', models.AutoField(primary_key=True, serialize=False)),
                ('price_band', models.CharField(blank=True, max_length=50, null=True)),
                ('open_date', models.DateField(blank=True, null=True)),
                ('close_date', models.DateField(blank=True, null=True)),
                ('issue_size', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_type', models.CharField(blank=True, max_length=50, null=True)),
                ('listing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Upcoming', 'Upcoming'), ('Open', 'Open'), ('Closed', 'Closed'), ('Listed', 'Listed')], default='Upcoming', max_length=10)),
                ('ipo_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('listing_gain', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_return', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipo_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('rhp_pdf', models.FileField(blank=True, null=True, upload_to='documents/rhp/')),
                ('drhp_pdf', models.FileField(blank=True, null=True, upload_to='documents/drhp/')),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipo_app.ipo')),
            ],
        ),
    ]
